apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: task-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          # Пробрасываем ВСЕ env-переменные из values.yaml
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          # === Spring Boot Actuator probes ===
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3